# Generated by Django 5.2 on 2025-04-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Mail', models.CharField(default='')),
                ('Mobile', models.BigIntegerField(default=0)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
